### ISSUE TITLE
error[E0046]: not all trait items implemented, missing: `description`

### ISSUE THREAD

**Issue by publicarray** [jedisct1/rust-doh#10]
I got this error when I tried updating rust-doh to 0.1.8 in my [docker image](https://github.com/publicarray/dns-resolver-infra/blob/master/doh-proxy/Dockerfile):

```
$ cargo install doh-proxy --version 0.1.8 --root /usr/local/
[...]
   Compiling doh-proxy v0.1.8
error[E0046]: not all trait items implemented, missing: `description`
  --> src/main.rs:70:1
   |
70 | impl std::error::Error for Error {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
   |
   = note: `description` from trait: `fn(&Self) -> &str`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
error: failed to compile `doh-proxy v0.1.8`, intermediate artifacts can be found at `/tmp/cargo-install1fPzaU`

Caused by:
  Could not compile `doh-proxy`.

To learn more, run the command again with --verbose.
```

**Comment by Yinchie** [comment]
`   Compiling doh-proxy v0.1.8
     Running `rustc --crate-name doh_proxy src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=05e6c42a115de4dc -C extra-filename=-05e6c42a115de4dc --out-dir /tmp/cargo-install.IrhzGFqM76HI/release/deps -L dependency=/tmp/cargo-install.IrhzGFqM76HI/release/deps --extern hyper=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libhyper-c6d35c3382083ef1.rlib --extern tokio=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio-2ea394153fc0f723.rlib --extern base64=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libbase64-f5359c7c3efd6bb5.rlib --extern clap=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libclap-120130469b13390e.rlib --extern tokio_timer=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio_timer-681184f838b055f9.rlib --extern futures=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libfutures-ec150b2f20f1f8e0.rlib --cap-lints allow`
error[E0046]: not all trait items implemented, missing: `description`
  --> src/main.rs:70:1
   |
70 | impl std::error::Error for Error {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
   |
   = note: `description` from trait: `fn(&Self) -> &str`

error: aborting due to previous error

error: failed to compile `doh-proxy v0.1.8`, intermediate artifacts can be found at `/tmp/cargo-install.IrhzGFqM76HI`

Caused by:
  Could not compile `doh-proxy`.

Caused by:
  process didn't exit successfully: `rustc --crate-name doh_proxy src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=05e6c42a115de4dc -C extra-filename=-05e6c42a115de4dc --out-dir /tmp/cargo-install.IrhzGFqM76HI/release/deps -L dependency=/tmp/cargo-install.IrhzGFqM76HI/release/deps --extern hyper=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libhyper-c6d35c3382083ef1.rlib --extern tokio=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio-2ea394153fc0f723.rlib --extern base64=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libbase64-f5359c7c3efd6bb5.rlib --extern clap=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libclap-120130469b13390e.rlib --extern tokio_timer=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio_timer-681184f838b055f9.rlib --extern futures=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libfutures-ec150b2f20f1f8e0.rlib --cap-lints allow` (exit code: 101)`

**Comment by Yinchie** [comment]
Same.

```
   Compiling doh-proxy v0.1.8
     Running `rustc --crate-name doh_proxy src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=05e6c42a115de4dc -C extra-filename=-05e6c42a115de4dc --out-dir /tmp/cargo-install.IrhzGFqM76HI/release/deps -L dependency=/tmp/cargo-install.IrhzGFqM76HI/release/deps --extern hyper=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libhyper-c6d35c3382083ef1.rlib --extern tokio=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio-2ea394153fc0f723.rlib --extern base64=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libbase64-f5359c7c3efd6bb5.rlib --extern clap=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libclap-120130469b13390e.rlib --extern tokio_timer=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio_timer-681184f838b055f9.rlib --extern futures=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libfutures-ec150b2f20f1f8e0.rlib --cap-lints allow`
error[E0046]: not all trait items implemented, missing: `description`
  --> src/main.rs:70:1
   |
70 | impl std::error::Error for Error {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `description` in implementation
   |
   = note: `description` from trait: `fn(&Self) -> &str`

error: aborting due to previous error

error: failed to compile `doh-proxy v0.1.8`, intermediate artifacts can be found at `/tmp/cargo-install.IrhzGFqM76HI`

Caused by:
  Could not compile `doh-proxy`.

Caused by:
  process didn't exit successfully: `rustc --crate-name doh_proxy src/main.rs --crate-type bin --emit=dep-info,link -C opt-level=3 -C metadata=05e6c42a115de4dc -C extra-filename=-05e6c42a115de4dc --out-dir /tmp/cargo-install.IrhzGFqM76HI/release/deps -L dependency=/tmp/cargo-install.IrhzGFqM76HI/release/deps --extern hyper=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libhyper-c6d35c3382083ef1.rlib --extern tokio=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio-2ea394153fc0f723.rlib --extern base64=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libbase64-f5359c7c3efd6bb5.rlib --extern clap=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libclap-120130469b13390e.rlib --extern tokio_timer=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libtokio_timer-681184f838b055f9.rlib --extern futures=/tmp/cargo-install.IrhzGFqM76HI/release/deps/libfutures-ec150b2f20f1f8e0.rlib --cap-lints allow` (exit code: 101)
```

**Comment by publicarray** [comment]
@jedisct1 Any idea on how to fix this one?

**Comment by jedisct1** [comment]
What version of Rust is that with? I wasn't able to reproduce this, neither with rust `stable` nor `nightly`.

**Comment by Yinchie** [comment]
1.25.0

**Comment by publicarray** [comment]
Thanks for double checking [Alpine 3.8 has 1.26.2](https://pkgs.alpinelinux.org/package/v3.8/community/x86_64/rust) which is a bit over [2 months behind](https://github.com/rust-lang/rust/releases) the stable version. I suppose I need to get rust from sh.rustup.rs

**Comment by Yinchie** [comment]
I am upgrading Rust as well. seems latest 1.28

**Comment by jedisct1** [comment]
Indeed, the `description()` function has been deprecated https://doc.rust-lang.org/std/error/trait.Error.html and is not required any more.

But since it's apparently okay to leave it no matter what, I added a minimal implementation, so rust-doh can still be compiled with old rust versions.

**Comment by publicarray** [comment]
Thanks for the patch 👍
