### ISSUE TITLE
dig slower than this doh-server written in golang

### ISSUE THREAD

**Issue by ookangzheng** [jedisct1/rust-doh#17]
I'm not sure what problem cause dig slower than rust-doh
Before I use this https://github.com/m13253/dns-over-https as doh-server
my client using dnscrypt-proxy to do DNS resolution. I try to dig some domain and normally it takes under 80 ms. While I switch to rust-doh, it takes about 250ms? 
Maybe rust-doh doesn't support JSON format only DNS-message format make it slower?

**Comment by jedisct1** [comment]
Even 80 ms is extremely slow for a DNS lookup. JSON adds some extra overhead and can only makes things slower, so the problem is different.

What upstream resolver are you sending the queries to?

In order to compare proxies, queries should be sent to a local resolver, possibly on the same machine, for queries that have been already cached.
