### ISSUE TITLE
Missing Cargo.lock

### ISSUE THREAD

**Issue by kpcyrd** [jedisct1/rust-doh#31]
Since this is a binary project it should distribute its Cargo.lock. Some distros depend on it for reproducible builds.

**Comment by jedisct1** [comment]
Hi!

I'm not a big fan of having a `Cargo.lock` file in the source code, rather than a minimum version.

When the project is being compiled, it's nice to have the latest compatible version of all dependencies, rather than aging, possibly insecure or broken (due to changes in the compiler) versions that have been hard-coded in a `Cargo.lock` file.

This is an executable file, so it doesn't matter much, but with libraries, these `Cargo.lock` file also tend to require many versions of the exact same sub-dependencies, just because the dependencies include`Cargo.lock` files generated at different times.

For building reproducible packages, you may want to add this `Cargo.lock` file.

But I'd prefer to avoid including it in the project.
