### ISSUE TITLE
doh-proxy works with doh-stub but not with firefox

### ISSUE THREAD

**Issue by Chaz6** [jedisct1/rust-doh#9]
I have set up an instance of doh-proxy at https://www.chaz6.com/dns-query (via an nginx proxy). I have verified it works with doh-stub, however when I set the following in Firefox (both latest stable and beta), dns resolution fails, and I am unsure what is wrong.

```
network.trr.uri = https://www.chaz6.com/dns-query
network.trr.mode = 3
network.trr.bootstrapAddress = 176.9.40.67
```

I would appreciate any help to find out what is broken.

**Comment by jedisct1** [comment]
I found the Firefox `trr.mode=3` to be extremely unreliable. Once it starts working, it's fine, but at least on MacOS, it often just doesn't send anything at all.

Changing `network.trr.bootstrapAddress` to some random address back and forth seems to help start the process.

Also note that `network.trr.bootstrapAddress` has to be the IP address of a DoH server, this is not a bootstrap DNS server as in dnscrypt-proxy.

Which is why I'm wondering if the startup issue is not due to it requiring a valid certificate for `https://<bootstrap ip>`. That would explain why it seems to be more reliable with Cloudflare.
